### ISSUE TITLE
Not sure why it still says it but...

### ISSUE THREAD

**Issue by devdot4** [TanukiSharp/DarkSoulsCloudSave#1]
![untitled](https://user-images.githubusercontent.com/15527358/27985989-79d41db4-63c5-11e7-8daf-2595e17a8df0.png)

Failed to initialize DropboxCloudStorage

Everything is up to par to your readme.

**Comment by TanukiSharp** [comment]
Are you running a prebuilt binary, or from the source code you built yourself ?
If you run from the code, could you set some breakpoints in order to get a bit more information ?

Are you running DarkSoulsCloudSave from a location where you have write access ? (e.g. NOT Program Files)

**Comment by devdot4** [comment]
Hello TanukiSharp, I am running a prebuilt binary and it has write access. I also created a new dropbox account to test it on (because my previous one already had been used previously. Both of them aren't working. I will test it more to let you know if it works or not. Thanks for a response.

**Comment by TanukiSharp** [comment]
Actually I just figured out I introduced a huge bug in version 1.0.5 (a dependency is missing) and I fixed it in version 1.0.6 which I just uploaded, if you could try this one.

I'm sorry for the trouble you encountered with version 1.0.5.

Please let me know if version 1.0.6 fixed your problem.

**Comment by devdot4** [comment]
1.0.6 is working perfectly, thanks a lot. I am glad we resolved this issue.
